version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-build-deploy:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - run:
          name: Ensure working directory exists on server
          command: |
            sudo apt-get update
            sudo apt-get install -y sshpass rsync
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "
            mkdir -p /root/candid"
      - run:
          name: Clone repository on server
          command: |
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "
            cd /root/candid
            git clone https://github.com/Cooperation-org/validator-service.git && git checkout main. || (cd /root/candid && git pull origin main)"
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Install additional packages
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit
      - store_test_results:
          path: /test-results/
      - run:
          name: Install SSH dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y sshpass rsync
      - run:
          name: Build and deploy project
          command: |
            sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "
            cd /root/candid
            npm install
            npm run build
            pm2 delete all || true
            pm2 start dist/index.js
            systemctl restart nginx"

workflows:
  build-and-test-deploy:
    jobs:
      - test-build-deploy
